# -*- coding: utf-8 -*-
"""Detection and validation of the acroform tags of a signable file.

A signable file may carry one tag per signer, telling the external signing service where to
paste the signature image, like {{#"ID":"Signer1","Size":{"Height":"70","Width":"200"}#}}
and one seal tag, for the seal image, like
{{#"ID":"SCEAU","Size":{"Height":"200","Width":"200"}#}}
"""

from collections import OrderedDict
from imio.esign import _
from imio.esign import logger
from imio.esign.interfaces import IContextUidProvider
from imio.esign.utils import get_session_info
from imio.helpers.content import uuidToObject
from io import BytesIO
from Products.CMFPlone.utils import safe_unicode
from xml.sax.saxutils import unescape
from zope.component import getAdapter
from zope.i18n import translate

import re
import subprocess
import zipfile


ACROFORM_TAG_RE = re.compile(r"\{\{#(.*?)#\}\}")
SIGNER_ID_RE = re.compile(r'"ID":"Signer(0|[1-9]\d*)"')
SEAL_ID_RE = re.compile(r'"ID":"SCEAU"')
XML_TAG_RE = re.compile(r"<[^>]*>")
WHITESPACE_RE = re.compile(r"\s+")
PDFTOTEXT = "pdftotext"

# content type -> path, inside the zipped document, of the xml part holding the text
ZIPPED_XML_PARTS = {
    "application/vnd.oasis.opendocument.text": "content.xml",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "word/document.xml",
}


def _pdf_text(data):
    """Return the text of a pdf, read by the poppler pdftotext binary."""
    process = subprocess.Popen(
        [PDFTOTEXT, "-q", "-enc", "UTF-8", "-", "-"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    out, err = process.communicate(data)
    if process.returncode != 0:
        raise RuntimeError("pdftotext failed: {}".format(err))
    return safe_unicode(out)


def _zipped_xml_text(data, part_name):
    """Return the text of the given xml part of a zipped document (odt, docx).

    The entities have to be resolved: a document generated by appy/POD stores the double
    quotes of a tag as &quot;, so the tag would never be recognised (PARAF-503).
    """
    zip_file = zipfile.ZipFile(BytesIO(data))
    try:
        xml = safe_unicode(zip_file.read(part_name))
    finally:
        zip_file.close()
    return unescape(XML_TAG_RE.sub(u" ", xml), {u"&quot;": u'"', u"&apos;": u"'"})


def extract_text(nbf):
    """Return the text of a file field, with every whitespace character removed."""
    if nbf is None or not getattr(nbf, "data", None):
        return u""
    try:
        if nbf.contentType == "application/pdf":
            text = _pdf_text(nbf.data)
        elif nbf.contentType in ZIPPED_XML_PARTS:
            text = _zipped_xml_text(nbf.data, ZIPPED_XML_PARTS[nbf.contentType])
        else:
            return u""
    except OSError:
        logger.error("Cannot run '%s': the signature tags of pdf files are not checked!", PDFTOTEXT)
        return u""
    except Exception:
        logger.debug("Could not extract the text of file '%s'", nbf.filename, exc_info=True)
        return u""
    return WHITESPACE_RE.sub(u"", text)


def get_tag_ids(nbf):
    """Return the acroform tag ids of a file field, reading its text only once.

    :return: the signer number of every signature tag, in document order, and the number
             of seal tags
    """
    numbers = []
    seals = 0
    for payload in ACROFORM_TAG_RE.findall(extract_text(nbf)):
        match = SIGNER_ID_RE.search(payload)
        if match:
            numbers.append(int(match.group(1)))
        elif SEAL_ID_RE.search(payload):
            seals += 1
    return numbers, seals


def validate_signer_numbers(numbers, nb_signers):
    """Return the acroform tag error messages for one file.

    A file is valid when it holds no tag at all, or exactly one tag per signer from Signer1
    to Signer<nb_signers>
    """
    if not numbers:
        return []
    counts = {}
    for nb in numbers:
        counts[nb] = counts.get(nb, 0) + 1
    errors = []
    for nb in sorted(counts):
        if counts[nb] > 1:
            errors.append(_("The signature tag of Signer${nb} is present ${count} times.",
                            mapping={"nb": nb, "count": counts[nb]}))
        if nb < 1 or nb > nb_signers:
            errors.append(_("There is a signature tag for Signer${nb} but ${count} signer(s) are defined.",
                            mapping={"nb": nb, "count": nb_signers}))
    for nb in range(1, nb_signers + 1):
        if nb not in counts:
            errors.append(_("The signature tag of Signer${nb} is missing.", mapping={"nb": nb}))
    return errors


def validate_seal_count(count, seal):
    """Return the acroform seal tag error messages for one file.

    A file is valid when it holds no seal tag, or exactly one while a seal is defined.
    """
    if not count:
        return []
    if not seal:
        return [_("There is a seal tag but no seal is defined.")]
    if count > 1:
        return [_("The seal tag is present ${count} times.", mapping={"count": count})]
    return []


def check_file(obj, nb_signers, seal=False):
    """Return the acroform tag error messages of a content object holding a file.

    :param nb_signers: number of signers, or None when the signature tags are unused
    :param seal: whether a seal is defined on the container
    """
    numbers, seal_count = get_tag_ids(getattr(obj, "file", None))
    errors = [] if nb_signers is None else validate_signer_numbers(numbers, nb_signers)
    return errors + validate_seal_count(seal_count, seal)


def get_session_acroform_errors(session_id):
    """Return the acroform tag errors of the files of a session, checked against its signers.

    :param session_id: internal session id
    :return: OrderedDict {file uid: (file object, context uid, [error messages])}, holding
             only the files in error
    """
    res = OrderedDict()
    session = get_session_info(session_id)
    if not session:
        return res
    nb_signers = len(session.get("signers", []))
    for file_info in session["files"]:
        obj = uuidToObject(uuid=file_info["uid"], unrestricted=True)
        if obj is None:
            continue
        errors = check_file(obj, nb_signers, session.get("seal", False))
        if errors:
            context_uid = getAdapter(obj, IContextUidProvider).get_context_uid()
            res[file_info["uid"]] = (obj, context_uid, errors)
    return res


def format_errors(pairs, request):
    """Return a one line readable summary of acroform tag errors.

    :param pairs: iterable of (file object, [error messages])
    :param request: used to translate the messages
    """
    return u" / ".join(
        [
            u"{}: {}".format(
                safe_unicode(obj.Title()), u" ".join([translate(msg, context=request) for msg in messages])
            )
            for obj, messages in pairs
        ]
    )
